set(groot, ...
'DefaultFigureColor', 'w', ...
'DefaultAxesLineWidth', 0.5, ...
'DefaultAxesXColor', 'k', ...
'DefaultAxesYColor', 'k', ...
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontSize', 11, ...
'DefaultAxesFontName', 'Arial', ...
'DefaultLineLineWidth', 0.5, ...
'DefaultTextFontUnits', 'Points', ...
'DefaultTextFontSize', 11, ...
'DefaultTextFontName', 'Arial', ...
'DefaultAxesBox', 'off',...
'DefaultAxesTickLength', [0 0]);
 
% set the tickdirs to go out - need this specific order
set(groot, 'DefaultAxesTickDir', 'in');
set(groot, 'DefaultAxesTickDirMode', 'manual');
